package com.hbm.ntm.network;

import net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent;

public final class ModNetwork {
    private static final String PROTOCOL_VERSION = "1";

    private ModNetwork() {
    }

    public static void register(RegisterPayloadHandlersEvent event) {
        var registrar = event.registrar(PROTOCOL_VERSION);
        registrar.playToClient(
                AssemblyRecipeSyncPayload.TYPE,
                AssemblyRecipeSyncPayload.STREAM_CODEC,
                AssemblyRecipeSyncPayload::handle
        );
        registrar.playToClient(
                GuideBookOpenPayload.TYPE,
                GuideBookOpenPayload.STREAM_CODEC,
                GuideBookOpenPayload::handle
        );
        registrar.playToClient(
                DetonatorInfoPayload.TYPE,
                DetonatorInfoPayload.STREAM_CODEC,
                DetonatorInfoPayload::handle
        );
        registrar.playToClient(
                MoonStatePayload.TYPE,
                MoonStatePayload.STREAM_CODEC,
                MoonStatePayload::handle
        );
        registrar.playToClient(
                SunStatePayload.TYPE,
                SunStatePayload.STREAM_CODEC,
                SunStatePayload::handle
        );
        registrar.playToServer(
                MoonDebrisImpactPayload.TYPE,
                MoonDebrisImpactPayload.STREAM_CODEC,
                MoonDebrisImpactPayload::handle
        );
        registrar.playToServer(
                AssemblySelectRecipePayload.TYPE,
                AssemblySelectRecipePayload.STREAM_CODEC,
                AssemblySelectRecipePayload::handle
        );
        registrar.playToServer(
                ChemicalPlantSelectPayload.TYPE,
                ChemicalPlantSelectPayload.STREAM_CODEC,
                ChemicalPlantSelectPayload::handle
        );
        registrar.playToServer(
                SolderingCollisionPayload.TYPE,
                SolderingCollisionPayload.STREAM_CODEC,
                SolderingCollisionPayload::handle
        );
        registrar.playToServer(
                FluidIdentifierSelectPayload.TYPE,
                FluidIdentifierSelectPayload.STREAM_CODEC,
                FluidIdentifierSelectPayload::handle
        );
        registrar.playToServer(
                HeatExchangerControlPayload.TYPE,
                HeatExchangerControlPayload.STREAM_CODEC,
                HeatExchangerControlPayload::handle
        );
        registrar.playToServer(
                NukeFstbmbButtonPayload.TYPE,
                NukeFstbmbButtonPayload.STREAM_CODEC,
                NukeFstbmbButtonPayload::handle
        );
        registrar.playToServer(
                DfcControlPayload.TYPE,
                DfcControlPayload.STREAM_CODEC,
                DfcControlPayload::handle
        );
        registrar.playToServer(
                FluidStorageTankModePayload.TYPE,
                FluidStorageTankModePayload.STREAM_CODEC,
                FluidStorageTankModePayload::handle
        );
        registrar.playToServer(
                RadioTorchConfigPayload.TYPE,
                RadioTorchConfigPayload.STREAM_CODEC,
                RadioTorchConfigPayload::handle
        );
        registrar.playToClient(
                VomitPayload.TYPE,
                VomitPayload.STREAM_CODEC,
                VomitPayload::handle
        );
        registrar.playToClient(
                GibletPayload.TYPE,
                GibletPayload.STREAM_CODEC,
                GibletPayload::handle
        );
        registrar.playToClient(
                StirlingStatePayload.TYPE,
                StirlingStatePayload.STREAM_CODEC,
                StirlingStatePayload::handle
        );
        registrar.playToClient(
                SawmillStatePayload.TYPE,
                SawmillStatePayload.STREAM_CODEC,
                SawmillStatePayload::handle
        );
        registrar.playToClient(
                SteamEngineStatePayload.TYPE,
                SteamEngineStatePayload.STREAM_CODEC,
                SteamEngineStatePayload::handle
        );
        registrar.playToClient(
                IndustrialTurbineStatePayload.TYPE,
                IndustrialTurbineStatePayload.STREAM_CODEC,
                IndustrialTurbineStatePayload::handle
        );
        registrar.playToClient(
                PumpStatePayload.TYPE,
                PumpStatePayload.STREAM_CODEC,
                PumpStatePayload::handle
        );
        registrar.playToClient(
                SteamCondenserStatePayload.TYPE,
                SteamCondenserStatePayload.STREAM_CODEC,
                SteamCondenserStatePayload::handle
        );
        registrar.playToClient(
                ChargeStatePayload.TYPE,
                ChargeStatePayload.STREAM_CODEC,
                ChargeStatePayload::handle
        );
        registrar.playToClient(
                ChargeBlastPayload.TYPE,
                ChargeBlastPayload.STREAM_CODEC,
                ChargeBlastPayload::handle
        );
        registrar.playToClient(
                MineBlastPayload.TYPE,
                MineBlastPayload.STREAM_CODEC,
                MineBlastPayload::handle
        );
        registrar.playToServer(
                AnvilCraftPayload.TYPE,
                AnvilCraftPayload.STREAM_CODEC,
                AnvilCraftPayload::handle
        );
        registrar.playToServer(
                GunInputPayload.TYPE,
                GunInputPayload.STREAM_CODEC,
                GunInputPayload::handle
        );
        registrar.playToClient(
                GunEffectPayload.TYPE,
                GunEffectPayload.STREAM_CODEC,
                GunEffectPayload::handle
        );
        registrar.playToServer(
                DntJetpackInputPayload.TYPE,
                DntJetpackInputPayload.STREAM_CODEC,
                DntJetpackInputPayload::handle
        );
        registrar.playToClient(
                DntJetpackStatePayload.TYPE,
                DntJetpackStatePayload.STREAM_CODEC,
                DntJetpackStatePayload::handle
        );
    }
}
